In [1]:
import open3d as o3d
import cv2
import numpy as np
from matplotlib import pyplot as plt
# import open3d_example as o3dtut

# import open3d_tutorial as o3dtut

#from open3d.geometry import sample_points_poisson_disk


print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Load a ply point cloud, print it, and render it
PointCloud with 196133 points.
[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]


In [2]:
# Create empty point cloud
# source: https://github.com/isl-org/Open3D/issues/986
pcl = o3d.geometry.PointCloud()
pcl.points = o3d.utility.Vector3dVector(np.random.randn(500,3))
o3d.visualization.draw_geometries([pcl])

In [15]:

bunny = o3d.data.BunnyMesh()
# mesh = o3dtut.get_bunny_mesh()
print(bunny.path)
print(type(bunny))

mesh = o3d.io.read_triangle_mesh(bunny.path)
mesh.compute_vertex_normals()
#o3d.visualization.draw_geometries([mesh])

# pcd = o3d.geometry.sample_points_poisson_disk(750)
# o3d.visualization.draw_geometries([pcd])
# alpha = 0.03pcd
# print(f"alpha={alpha:.3f}")
# mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha)
# mesh.compute_vertex_normals()
# o3d.visualization.draw_geometries([mesh], mesh_show_back_face=True)

ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

alpha = 0.03
print(f"alpha={alpha:.3f}")
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha)
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh], mesh_show_back_face=True)

/home/arthur/open3d_data/extract/BunnyMesh/BunnyMesh.ply
<class 'open3d.cpu.pybind.data.BunnyMesh'>
alpha=0.030


In [3]:
bunny = o3d.data.BunnyMesh()
print(bunny.path)
print(type(bunny))

mesh = o3d.io.read_triangle_mesh(bunny.path)
mesh.compute_vertex_normals()

ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

tetra_mesh, pt_map = o3d.geometry.TetraMesh.create_from_point_cloud(pcd)
for alpha in np.logspace(np.log10(0.5), np.log10(0.01), num=4):
    print(f"alpha={alpha:.3f}")
    mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(
        pcd, alpha, tetra_mesh, pt_map)
    mesh.compute_vertex_normals()
    o3d.visualization.draw_geometries([mesh], mesh_show_back_face=True)

/home/arthur/open3d_data/extract/BunnyMesh/BunnyMesh.ply
<class 'open3d.cpu.pybind.data.BunnyMesh'>
alpha=0.500
alpha=0.136
alpha=0.037
alpha=0.010


In [5]:
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)
bunny = o3d.data.BunnyMesh()
# mesh = o3dtut.get_bunny_mesh()
print(bunny.path)
print(type(bunny))

mesh = o3d.io.read_triangle_mesh(bunny.path)


distances = pcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 3 * avg_dist

mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting( \
    pcd,o3d.utility.DoubleVector([radius, radius * 2]))

mesh.compute_vertex_normals()
print(mesh)

ply_point_cloud = o3d.data.PLYPointCloud()

tetra_mesh, pt_map = o3d.geometry.TetraMesh.create_from_point_cloud(pcd)
for alpha in np.logspace(np.log10(0.5), np.log10(0.01), num=4):
    print(f"alpha={alpha:.3f}")
    mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(
        pcd, alpha, tetra_mesh, pt_map)
    mesh.compute_vertex_normals()
    o3d.visualization.draw_geometries([mesh], mesh_show_back_face=True)

TriangleMesh with 196133 points and 330807 triangles.
alpha=0.500
alpha=0.136
alpha=0.037
alpha=0.010
